version: '3'

services:
  dynamodb-local:
    container_name: test_dynamodb-local
    image: amazon/dynamodb-local:latest
    user: root
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - dynamodb-local-data:/data
    ports:
      - 8000:8000
    networks:
      - dynamodb-local-network

  dynamodb-admin:
    container_name: test_dynamodb-admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=dynamodb-local:8000
    ports:
      - 8001:8001
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network
  app:
    container_name: app
    image: sampleapp:0.5.0
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 9000:8080
    depends_on:
      - dynamodb-local
    networks:
      - dynamodb-local-network
    environment:
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000

  
volumes:
  dynamodb-local-data:

networks:
  dynamodb-local-network:
    driver: bridge